version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y curl unzip
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle
            gradle --version
      - run:
          name: Build JAR
          command: ./gradlew shadowJar
      - run:
          name: Generate SHA256
          command: |
            shasum -a 256 build/libs/DML-all.jar | awk '{ print $1 }' > checksum.txt
      - run:
          name: Clone and update homebrew-dml formula
          command: |
            git config --global user.name "tree-ci"
            git config --global user.email "ci@tree.software"
            
            git clone https://github.com/tree-software-company/homebrew-dml.git
            cd homebrew-dml

            JAR_URL="https://github.com/tree-software-company/dml/releases/latest/download/DML-all.jar"
            SHA256=$(cat ../checksum.txt)

            cat > dml.rb <<'EOF'
            class Dml < Formula
              desc "Custom DSL for data definition like JSON, with Kotlin & ANTLR"
              homepage "https://github.com/tree-software-company/dml"
              url "$JAR_URL"
              sha256 "$SHA256"
              license "Apache-2.0"

              def install
                libexec.install "DML-all.jar"
                (bin/"dml").write <<~EOS
                  #!/bin/bash
                  exec java -jar "\#{libexec}/DML-all.jar" "\$@"
                EOS
              end

              test do
                assert_match "DML Command Line Interface", shell_output("\#{bin}/dml help")
              end
            end
            EOF

            git add dml.rb
            git commit -m "Update formula with new release"
            git push https://$HOMEBREW_TOKEN@github.com/tree-software-company/homebrew-dml.git HEAD:main

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
