version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    environment:
      NEW_VERSION: "0.1.0"
      SHA256: "596eff26ac018c27553a05cf62ef4f1af35f8c7d7ca40b548985ad9f5d472b99"
    steps:
      - checkout
      - run:
          name: Setup SSH
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Clone and update homebrew-dml formula
          command: |
            git config --global user.name "simon04PL"
            git config --global user.email "szymon.msa@gmail.com"
            
            git clone git@github.com:tree-software-company/homebrew-dml.git
            cd homebrew-dml
            
            cat > dml.rb \<<EOF
            class Dml < Formula
              desc "Custom DSL for data definition like JSON, with Kotlin & ANTLR"
              homepage "https://github.com/tree-software-company/DML"
              url "https://github.com/tree-software-company/DML/releases/download/0.1.0/DML-all.jar"
              version "0.1.0.1"
              sha256 "596eff26ac018c27553a05cf62ef4f1af35f8c7d7ca40b548985ad9f5d472b99"
              license "Apache-2.0"
            
              def install
                libexec.install "DML-all.jar"
                (bin/"dml").write <<~EOS
                  #!/bin/bash
                  exec java -jar "\#{libexec}/DML-all.jar" "\$@"
                EOS
              end
            
              test do
                assert_match "DML Command Line Interface", shell_output("\#{bin}/dml help")
              end
            end
            EOF

            git add dml.rb
            git commit -m "Update formula with new release"
            git push git@github.com:tree-software-company/homebrew-dml.git HEAD:main

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
